[project]
name = "pysteg"
version = "0.1.0"
description = "A basic GUI for steganography"
authors = [
    { name = "KisSCoOl", email = "kisscool@kisscool.net" },
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "stegano>=2.1.0",
    "pyqt6>=6.10.2",
    "cryptography>=46.0.5",
]

[dependency-groups]
dev = [
    "pip-audit>=2.10.0",
    "pyright>=1.1.408",
    "pytest>=9.0.2",
    "ruff>=0.15.0",
]

[tool.pyright]
include = ["app"]
pythonVersion = "3.13"
typeCheckingMode = "strict"
venvPath = "."
venv = ".venv"
